server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 500
        format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false

  data:
    redis:
      host: ${REDIS_URL}
      port: ${REDIS_PORT}
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

  batch:
    jdbc:
      initialize-schema: always
    job:
      name: eventLogClearJob
#      enabled: false # Job 실행을 스케줄러에게 위임하기 위하여 설정

cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
    credentials:
      access-key: ${BUCKET_ACCESS_KEY}
      secret-key: ${BUCKET_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false


secret:
  pwd: ${SECRET_PWD}
  jwt: ${SECRET_JWT}
  geocodingApiKey: ${GEOCODING_API_KEY}