server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  profiles:
    active:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 500
        format_sql: true
    defer-datasource-initialization: true
  jackson:
    serialization:
      fail-on-empty-beans: false

secret:
  pwd: ${SECRET_PWD}
  jwt: ${SECRET_JWT}
  geocodingApiKey: ${SECRET_GEOCODING_API_KEY}